# Generated by Django 4.0.4 on 2022-06-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='active',
            new_name='is_active',
        ),
    ]
