# Generated by Django 4.0.4 on 2022-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graficas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('SKU', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'grafica',
                'verbose_name_plural': 'graficas',
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
