# Generated by Django 4.0.4 on 2022-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_procesadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficas',
            name='memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='procesadores',
            name='cache',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='procesadores',
            name='cores',
            field=models.IntegerField(null=True),
        ),
    ]
